language: node_js
node_js:
  - -10
  - -12
  - 12.14.0
branches:
  only:
    - master
    - /^greenkeeper/.*$/
notifications:
  email:
    - torstenlink@gmx.de
    - markus.felten@gmx.de
before_install:
  - npm i -g npm@latest
before_script:
  - npm prune
  - npm install -g codecov
  - npm install coveralls
script:
  - npm run cover
after_script:
  - codecov
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - npm run docs
after_success:
  - npm run semantic-release

cache: --delete-- npm
